site_name: 'Documentation | TACO: The Tensor Algebra Compiler'
site_favicon: favicon.ico
theme: readthedocs
extra_css: [extra.css]
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
    - markdown.extensions.admonition
    - markdown.extensions.fenced_code
    - pymdownx.superfences
use_directory_urls: false
nav:
    - C++ API:
        - 'Defining Tensors': 'tensors.md'
        - 'Computing on Tensors': 'computations.md'
        - 'Providing a Schedule': 'scheduling.md'
    - Python API:
        - 'Defining Tensors': 'pytensors.md'
        - 'Computing on Tensors': 'pycomputations.md'
        - 'Reference Manual': 'pyreference.md'
        - 'Tutorial': 'tutorial.md'
    - Example Applications:
        - 'Scientific Computing: SpMV': 'scientific_computing.md'
        - 'Data Analytics: MTTKRP': 'data_analytics.md'
        - 'Machine Learning: SDDMM': 'machine_learning.md'
    - Advanced Usage:
        - 'Strategies for Optimization': optimization.md
        - 'Guide to Benchmarking': benchmarking.md
